# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Lint package files
jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
